# meta_product_name: "Easy Lab"
# meta_title: "Easy Lab - Comprenez faciement vos analyses de laboratoires médicales"
# meta_description: "Comprenez vos analyses et suivez votre état de santé grâce à des tableaux de bords"
# meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
